import './globals.css'
import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import Header from './components/Header'

export const metadata: Metadata = {
  title: 'Eco Art Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header><Header /></header>
          {children}
          
          </body>
      </html>
    </ClerkProvider>
  )
}
